services:
  postgres:
    image: postgres:16-alpine
    container_name: match_alert_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: match_alert_user
      POSTGRES_PASSWORD: match_alert_password
      POSTGRES_DB: match_alert_db
    ports:
      - "5432:5432"
    volumes:
      - match_alert_postgres_data:/var/lib/postgresql/data

volumes:
  match_alert_postgres_data:
